import type { Order, User, Customer, DashboardStats } from './types';

export const DEMO_USERS: User[] = [
  {
    id: '1',
    name: 'José Sánchez',
    phone: '809-751-7628',
    role: 'admin',
    is_active: true,
    created_at: '2024-01-01',
  },
  {
    id: '2',
    name: 'Emely',
    phone: '849-265-2705',
    role: 'employee',
    is_active: true,
    created_at: '2024-01-15',
  },
  {
    id: '3',
    name: 'Victor Charlie',
    phone: '809-646-8420',
    role: 'delivery',
    is_active: true,
    created_at: '2024-02-01',
  },
  {
    id: '4',
    name: 'Argeni Castillo',
    phone: '849-274-2105',
    role: 'delivery',
    is_active: true,
    created_at: '2024-02-15',
  },
  {
    id: '5',
    name: 'Wilo Iglesia',
    phone: '829-792-8041',
    role: 'delivery',
    is_active: true,
    created_at: '2024-03-01',
  },
  {
    id: '6',
    name: 'Victor de la Rosa',
    phone: '849-886-2090',
    role: 'delivery',
    is_active: true,
    created_at: '2024-03-15',
  },
];

export const DEMO_CUSTOMERS: Customer[] = [
  {
    id: 'c1',
    name: 'María Pérez',
    phone: '809-555-1001',
    address: 'Calle El Sol #45, Ensanche Naco',
    sector: 'Ensanche Naco',
    order_count: 8,
    is_blacklisted: false,
    created_at: '2024-01-10',
  },
  {
    id: 'c2',
    name: 'Carlos Reyes',
    phone: '809-555-1002',
    address: 'Av. Lincoln #55, Piantini',
    sector: 'Piantini',
    order_count: 3,
    is_blacklisted: false,
    created_at: '2024-02-20',
  },
  {
    id: 'c3',
    name: 'Ana Gómez',
    phone: '809-555-1003',
    address: 'Calle Las Palmas #12, Los Prados',
    sector: 'Los Prados',
    order_count: 12,
    is_blacklisted: false,
    created_at: '2024-01-05',
  },
  {
    id: 'c4',
    name: 'Roberto Díaz',
    phone: '809-555-1004',
    address: 'Av. Independencia #200, Gazcue',
    sector: 'Gazcue',
    notes: 'Siempre pide talla L. Paga rápido.',
    order_count: 15,
    is_blacklisted: false,
    created_at: '2023-12-01',
  },
  {
    id: 'c5',
    name: 'Luis Martínez',
    phone: '809-555-1005',
    address: 'Calle Duarte #88, Zona Colonial',
    sector: 'Zona Colonial',
    notes: 'Ha devuelto 3 órdenes seguidas',
    order_count: 5,
    is_blacklisted: true,
    blacklist_reason: 'Devuelve todo y no paga delivery',
    created_at: '2024-03-10',
  },
];

export const DEMO_ORDERS: Order[] = [
  {
    id: 'o1',
    order_number: 'BS-2406-0247',
    customer_id: 'c1',
    customer: DEMO_CUSTOMERS[0],
    type: 'standard',
    status: 'preparing',
    items: [
      { id: 'i1', order_id: 'o1', product_name: 'Conjunto lino beige', size: 'M', quantity: 2, unit_price: 1800, is_try_fit: false, kept: null },
      { id: 'i2', order_id: 'o1', product_name: 'Poloche negra', size: 'L', quantity: 1, unit_price: 1250, is_try_fit: false, kept: null },
    ],
    subtotal: 4850,
    delivery_fee: 200,
    total: 5050,
    payment_method: 'transfer',
    payment_status: 'pending',
    source: 'whatsapp',
    priority: 'normal',
    product_photos: [],
    created_by: '2',
    created_at: new Date(Date.now() - 45 * 60000).toISOString(),
    updated_at: new Date(Date.now() - 20 * 60000).toISOString(),
  },
  {
    id: 'o2',
    order_number: 'BS-2406-0246',
    customer_id: 'c2',
    customer: DEMO_CUSTOMERS[1],
    type: 'try_fit',
    status: 'delivered',
    items: [
      { id: 'i3', order_id: 'o2', product_name: 'Camisa slim fit azul', size: 'M', quantity: 1, unit_price: 1800, is_try_fit: true, kept: null },
      { id: 'i4', order_id: 'o2', product_name: 'Camisa slim fit azul', size: 'L', quantity: 1, unit_price: 1800, is_try_fit: true, kept: null },
      { id: 'i4b', order_id: 'o2', product_name: 'Pantalón slim negro', size: '32', quantity: 1, unit_price: 2200, is_try_fit: true, kept: null },
      { id: 'i4c', order_id: 'o2', product_name: 'Pantalón slim negro', size: '34', quantity: 1, unit_price: 2200, is_try_fit: true, kept: null },
    ],
    subtotal: 4000,
    delivery_fee: 250,
    total: 4250,
    payment_method: 'cash',
    payment_status: 'pending',
    notes: 'Cliente quiere probar la M y L en camisa, y 32 y 34 en pantalón. Se queda con una de cada una.',
    source: 'instagram',
    priority: 'normal',
    product_photos: [],
    created_by: '2',
    assigned_delivery_id: '4',
    assigned_delivery: DEMO_USERS[3],
    created_at: new Date(Date.now() - 120 * 60000).toISOString(),
    updated_at: new Date(Date.now() - 30 * 60000).toISOString(),
  },
  {
    id: 'o3',
    order_number: 'BS-2406-0245',
    customer_id: 'c3',
    customer: DEMO_CUSTOMERS[2],
    type: 'standard',
    status: 'in_transit',
    items: [
      { id: 'i5', order_id: 'o3', product_name: 'Pantalón cargo', size: '32', quantity: 1, unit_price: 2200, is_try_fit: false, kept: null },
    ],
    subtotal: 2200,
    delivery_fee: 200,
    total: 2400,
    payment_method: 'transfer',
    payment_status: 'pending',
    source: 'whatsapp',
    priority: 'urgent',
    product_photos: [],
    created_by: '1',
    assigned_delivery_id: '3',
    assigned_delivery: DEMO_USERS[2],
    created_at: new Date(Date.now() - 90 * 60000).toISOString(),
    updated_at: new Date(Date.now() - 15 * 60000).toISOString(),
  },
  {
    id: 'o4',
    order_number: 'BS-2406-0244',
    customer_id: 'c4',
    customer: DEMO_CUSTOMERS[3],
    type: 'standard',
    status: 'completed',
    items: [
      { id: 'i6', order_id: 'o4', product_name: 'Conjunto deportivo', size: 'L', quantity: 1, unit_price: 2500, is_try_fit: false, kept: null },
      { id: 'i7', order_id: 'o4', product_name: 'Gorra BlackStore', quantity: 1, unit_price: 600, is_try_fit: false, kept: null },
    ],
    subtotal: 3100,
    delivery_fee: 150,
    total: 3250,
    payment_method: 'prepaid',
    payment_status: 'verified',
    source: 'store',
    priority: 'normal',
    product_photos: [],
    created_by: '1',
    assigned_delivery_id: '3',
    assigned_delivery: DEMO_USERS[2],
    created_at: new Date(Date.now() - 240 * 60000).toISOString(),
    updated_at: new Date(Date.now() - 180 * 60000).toISOString(),
  },
  {
    id: 'o5',
    order_number: 'BS-2406-0243',
    customer_id: 'c3',
    customer: DEMO_CUSTOMERS[2],
    type: 'standard',
    status: 'new',
    items: [
      { id: 'i8', order_id: 'o5', product_name: 'T-Shirt oversize', size: 'XL', color: 'Negro', quantity: 3, unit_price: 950, is_try_fit: false, kept: null },
    ],
    subtotal: 2850,
    delivery_fee: 200,
    total: 3050,
    payment_method: 'cash',
    payment_status: 'pending',
    source: 'whatsapp',
    priority: 'normal',
    product_photos: [],
    created_by: '2',
    created_at: new Date(Date.now() - 10 * 60000).toISOString(),
    updated_at: new Date(Date.now() - 10 * 60000).toISOString(),
  },
];

export const DEMO_STATS: DashboardStats = {
  orders_today: 20,
  orders_pending: 5,
  orders_in_transit: 3,
  orders_delivered: 12,
  revenue_today: 58750,
  payments_pending: 4,
  active_deliveries: 4,
};
